services:
  drupal:
    image: drupal:10
    container_name: drupal_app
    ports:
      - "8080:80"
    volumes:
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
      - ./profiles:/var/www/html/profiles
      - ./sites:/var/www/html/sites
    depends_on:
      - db
    entrypoint: >
      sh -c "composer require drush/drush &&
      drush site-install standard --db-url=mysql://drupal:drupal@db/drupal
      --site-name='Drupal Automático'
      --account-name=admin
      --account-pass=admin -y &&
      apache2-foreground"
  db:
    image: mariadb:10.6
    container_name: drupal_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql
volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  db_data:
